[package]
name = "liboverdrop"
version = "0.0.0"
authors = ["Luca Bruno <luca.bruno@coreos.com>"]
edition = "2018"

[dependencies]
error_chain = { package = "error-chain", version = "^0.12.1" }
log = "^0.4.6"
